Mm/add ckeditor npm run
PlexTrac/plextrac-manager-util pull request #114
Opened 2024-03-01 00:08 UTC by mmorgan-pt

This needs reviewed and tested, but should not be merged until the dependent code has been deployed. 
The necessary code is currently in edge, but has not been officially released as it is in QA currently.

2024-03-04 18:09 UTC, Michael-Burke commented on src/_configure_plextrac.sh
> +  CKEDITOR_JSON=`compose_client exec plextracapi npm run ckeditor:environment:migration | grep '^{' || log "ERROR: Unable to run ckeditor:environment:migration"`
Also you can check the presence of the script before invoking NPM via `--if-present`. I was able to test and get this working with something like:

```bash
if [ $(compose_client exec plextracapi npm run ckeditor:environment:migration --if-present) ]; then
    CKEDITOR_JSON=`compose_client exec plextracapi npm run ckeditor:environment:migration | grep '^{' || error "ERROR: Unable to run ckeditor:environment:migration"`
  else
    error "Can't find migration script for CKEditor"
    return 0
  fi
```

2024-03-04 18:09 UTC, Michael-Burke commented on src/_update.sh
> +}
This I added to help with a different bug -- no impact and hidden command

2024-03-13 14:31 UTC, skylerfenn commented on src/_configure_plextrac.sh
> +CKEDITOR_MIGRATE=true
@mmorgan-pt If this goes to production, `CKEDITOR_MIGRATE` should be false for now. We'll want to set this variable true for select customers as we are ready.

2024-03-13 21:22 UTC, Michael-Burke commented on src/_configure_plextrac.sh
> +  info "Please run "plextrac configure" as root to update the nginx configuration files"
Same for these instances below

2024-03-13 21:23 UTC, Michael-Burke commented on static/docker-compose.yml
> +      CKEDITOR_SERVER_CONFIG: ${CKEDITOR_SERVER_CONFIG}
If these don't exist, this will fail. Do you want to provide a blank string if the variable is missing here?

2024-03-13 21:23 UTC, Michael-Burke commented on static/docker-compose.yml
> +      REDIS_CONNECTION_STRING: redis://redis:6379
I think this may also be a different connection string unless a different redis is being stood up

2024-03-29 21:56 UTC, Michael-Burke requested changes
The main concerns are moving `mod_configure` and removal of requiring plextrac user for `plextrac install`

2024-03-29 21:56 UTC, Michael-Burke commented on src/_update.sh
> -  mod_configure
Why was this moved?

2024-03-29 21:56 UTC, Michael-Burke commented on src/plextrac
> -  requires_user_plextrac
This needs to stay

2024-04-22 21:10 UTC, Michael-Burke commented on src/plextrac
> +serviceNames=("plextracdb" "postgres" "redis" "ckeditor-backend" "plextracapi" "notification-engine" "notification-sender" "contextual-scoring-service" "migrations" "plextracnginx")
We should gate this behind boolean for CKEDITOR_MIGRATE

2024-05-02 22:24 UTC, mmorgan-pt commented
Now that we re-worked the base container, this PR is far simpler. This has been tested in production now with the config files being disabled. This latest commit simply cleans up the unused code, so this should be ready for production and to be merged into main

2024-05-07 19:29 UTC, mmorgan-pt reviewed
Tested this in ubuntu 22.04 and on rhel8 and everything looks good to me! This should be ready to merge

2024-05-07 20:35 UTC, Michael-Burke approved these changes

2024-05-07 20:37 UTC, merged