Update: Permission Check/Fix
PlexTrac/plextrac-manager-util pull request #85
Opened 2023-09-29 16:05 UTC by Michael-Burke

- Added permission check/fix for a known permission problem with the `etl-logs` folder

2023-10-05 22:24 UTC, Michael-Burke commented
@mmorgan-pt fixed the permission issue you described. Will not correctly instruct and check for root / sudo use to fix the issue when present

2023-10-09 21:53 UTC, mmorgan-pt requested changes

2023-10-09 21:53 UTC, mmorgan-pt commented on src/_check.sh
Line 13 (requires_user_plextrac) collides with the etl_fix for root owned directories. I think moving `mod_etl_fix` above this line would allow it to work. That's just one idea though. When I tested, it prompted me to run as sudo or root, but running as root prompts to run as plextrac user

2023-10-11 21:16 UTC, Michael-Burke commented on src/_check.sh
Adjusted the need for running as root, since I can exec as UID 0 in the container and adjust permissions there

2023-10-11 22:23 UTC, mmorgan-pt approved these changes
Nice find! clever and elegant solution!

2023-10-12 15:09 UTC, merged